export const REQUEST_IMAGE_PENDING = 'REQUEST_IMAGE_PENDING';
export const REQUEST_IMAGE_SUCCESS = 'REQUEST_IMAGE_SUCCESS';
export const REQUEST_IMAGE_FAILED = 'REQUEST_IMAGE_FAILED';
export const IMAGE_LOADED_SUCCESS = 'IMAGE_LOADED_SUCCESS';
export const IMAGE_LOADED_PENDING = 'IMAGE_LOADED_PENDING';
export const TWEET_CLICKED = 'TWEET_CLICKED';